<div id="breadcumb" class="wrapper">
	<h1><a href="index.php">Home</a> &raquo; <a href="">Syarat &amp; Ketentuan</a></h1>
</div><!-- end #breadcumb -->
<div id="container">
    <div class="wrapper">
        <div class="entry-post white_table">
        	<h1>Syarat &amp; Ketentuan</h1>
        	<ol>
                <li>"Layanan" adalah layanan seluler prabayar dan pasca bayar, dan segala  bentuk  layanan yang memberikan nilai tambah, melengkapi atau layanan tambahan yang kami sediakan kepada anda dari waktu ke waktu. "Syarat dan Ketentuan" adalah syarat dan ketentuan ini dan syarat layanan, kebijakan dan prosedur yang tertera di dalam Paket Perdana, petunjuk penggunaan yang dapat diubah atau dimodifikasi dari waktu ke waktu oleh AXIS sesuai dengan kebijaksanaannya.  "Paket Perdana" adalah paket yang dijual oleh AXIS termasuk didalamnya Kartu SIM (dengan nilai pulsa perdana), petunjuk penggunaan dan syarat dan kondisi yang berlaku.</li>
                <li>Selama diatur dalam peraturan perundang-undangan, Layanan diberikan dengan basis "sebagaimana adanya" dan "sebagaimana tersedia" dan AXIS tidak bertanggung jawab dan tidak memberikan pernyataan atau jaminan tersurat maupun tersirat atas apa pun terkait dengan Layanan termasuk namun tidak terbatas pada: <br>
                  <ol>
                    <li>kemampuan untuk diakses, ketepatan waktu, dan pemakaian tanpa sela dari Layanan tersebut; </li>
                    <li> tata urutan, keakuratan, kelengkapan, ketepatan waktu atau keamanan atas data atau informasi apapun yang ditransmisikan atau diterima oleh anda terkait dengan Layanan tersebut. </li>
                  </ol>
                  Anda harus mencari tahu sendiri kecukupan cakupan AXIS. </li>
                <li>AXIS tidak memiliki kewajiban apapun untuk mengganti atau memberikan kompensasi atas kehilangan, pencurian, kerusakan, kegagalan atau penggandaan Kartu SIM anda, voucher isi ulang, dan/atau untuk pulsa yang tidak digunakan. Jika AXIS memilih untuk menggganti Kartu SIM anda, anda dapat kami kenakan biaya penggantian dengan nilai yang akan kami tentukan kemudian. Anda menyadari bahwa tidak terdapat garansi untuk Kartu SIM, kecuali apabila terdapat cacat produksi pada Kartu SIM dan/atau voucher isi ulang. Anda harus mengupayakan segala cara untuk menghindari kerugian, pencurian atau penggunaan yang tidak semestinya dari dan/atau penggandaan Kartu SIM. Dalam hal terdapat kehilangan, pencurian atau penggunaan yang tidak semestinya dari Kartu SIM, anda harus segera memberitahu kami. Anda tetap bertanggung jawab atas segala tagihan dan biaya yang terkait dengan Kartu SIM termasuk semua biaya terkait dengan penggunaan yang tidak semestinya. </li>
                <li>AXIS dapat sewaktu-waktu berdasarkan penilaiannya dan tanpa melakukan pemberitahuan terlebih dahulu kepada pihak lainnya, mengubah, mengganti, menambah atau memodifikasi Layanan. AXIS tidak bertanggung jawab atas kerugian atau ketidaknyamanan anda yang timbul karena hal ini. </li>
                <li>AXIS, karyawan, pegawai dan agen AXIS tidak akan bertanggung jawab kepada anda atau pihak ketiga lainnya yang memiliki kewenangan dari atau melakukan klaim melalui anda atas:
                  <ol>
                    <li>Kehilangan atau kerugian yang anda terima diakibatkan oleh penangguhan/pengakhiran Layanan dan gangguan atas/tidak adanya Layanan atau bagian darinya yang diakibatkan apapun juga; </li>
                    <li>Kehilangan atau perubahan atau berkurangnya data yang timbul dari penggunaan Layanan untuk melakukan transmisi data atau untuk data komunikasi pada segala tahapan transmisi termasuk setiap akses secara melawan hukum atau tidak berwenang terhadap transmisi anda atau data anda; </li>
                    <li>Gangguan atau tidak adanya Layanan yang dikarenakan kondisi yang termasuk namun tidak terbatas pada, kondisi cuaca yang tidak bersahabat, gangguan elektromagnit, kepadatan pada jaringan atau sistem telekomunikasi. </li>
                  </ol>
                </li>
                <li>AXIS tidak bertanggung jawab atas, dan anda membebaskan AXIS dari segala klaim, kerugian, tanggung jawab, perkara, tuntutan, biaya, dan pengeluaran (termasuk biaya perkara) yang mungkin timbul atau yang AXIS mungkin derita sehubungan dengan atau yang timbul dari penyediaan Layanan kepada anda </li>
                <li>AXIS berhak, berdasarkan kebijaksanaanya secara mutlak, memberhentikan atau mencabut akses kepada Layanan tanpa pemberitahuan terlebih dahulu atau ganti rugi kepada anda:
                  <ol>
                    <li>apabila terjadi gangguan teknis pada Layanan atau jaringan;</li>
                    <li>ketika dilakukan peningkatan, modifikasi atau pemeliharaan atas Layanan;</li>
                    <li>apabila anda melanggar salah satu ketentuan di dalam Syarat dan Ketentuan ini;</li>
                    <li>apabila anda melakukan tindakan yang, menurut pendapat kami, dapat menimbulkan kerusakan atau gangguan pada Layanan atau jaringan;</li>
                    <li>Jika AXIS diharuskan Undang-undang, ketentuan hukum, peraturan perundang-undangan atau pejabat yang berwenang untuk melakukan hal tersebut;</li>
                    <li>Jika menurut pendapat kami dan berdasarkan penilaian kami, Layanan dan jaringan digunakan secara tidak tepat, tidak sah atau dengan maksud untuk melawan hukum, termasuk namun tidak terbatas pada pengiriman pesan yang tidak diminta dan dalam jumlah besar (spam). </li>
                  </ol>
                </li>
                <li>Tanpa membatasi keberlakuan umum atas Syarat dan Ketentuan, AXIS tidak bertanggung jawab atas ketidakmampuan untuk melaksanakan kewajibannya yang disebabkan adanya Bencana Alam, pemberontakan, operasi militer atau terorisme, segala keadaan darurat, tindakan atau tidak adanya tindakan oleh pemerintah atau pihak berwenang, sengketa industrial dalam bentuk apapun, kebakaran, badai, ledakan, bencana banjir, tindakan atau tidak adanya tindakan oleh orang atau badan terhadap siapa AXIS tidak memiliki kemampuan untuk mengontrol atau sebab apapun juga yang di luar kemampuan wajar kami.</li>
                <li>AXIS dapat mengalihkan atau melakukan novasi atas seluruh atau sebagian dari Syarat dan Ketentuan kepada pihak ketiga manapun dengan memberikan pemberitahuan kepada anda tanpa diperlukan persetujuan dari anda sebelumnya. Anda tidak dapat mengalihkan atau melakukan novasi atas hak/kewajiban anda di sini kepada pihak lainnya tanpa persetujuan tertulis sebelumnya dari AXIS. </li>
                <li>Syarat dan Ketentuan dapat diubah dan Syarat dan Ketentuan yang berlaku yang terdapat pada website akan berlaku dan menggantikan setiap dan seluruh versi sebelumnya, termasuk yang tertera di dalam petunjuk penggunaan atau syarat dan ketentuan di dalam Paket Perdana. Anda bertanggung jawab untuk selalu membaca informasi terkait dengan Layanan yang dimasukkan kedalam alamat website kami yang mungkin termasuk perubahan atas Syarat dan Ketentuan.</li>
                <li>Penggunaan Layanan oleh anda setelah tanggal berlakunya perubahan Syarat dan Ketentuan akan dianggap sebagai persetujuan tanpa syarat oleh anda atas segala perubahan, variasi dan penambahan dan anda terikat oleh mereka, Jika anda tidak menyetujui perubahan tersebut, anda berhak untuk mengakhiri penggunaan Layanan.</li>
                <li>Dengan menggunakan Layanan berarti anda setuju memberikan ganti rugi kepada dan membebaskan kami beserta pejabat, karyawan dan agen kami atas segala kehilangan, kerusakan, tanggung jawab atau pengeluaran yang timbul dari adanya klaim atas fitnah, gangguan atas privasi, pelanggaran atas hak cipta, paten, pelanggaran kerahasiaan atau hak, atau pelanggaran atas ketentuan perundang-undangan atau apapun juga yang timbul dari materi yang ditransmisikan, diterima atau disimpan melalui Layanan atau sebagian dari hal tersebut, dan dari segala klaim lainnya yang timbul dari tindakan atau tiadanya tindakan dari anda atau penggunaan atau eksploitasi secara tidak berwenang atas Layanan atau bagian dari Layanan.</li>
                <li>AXIS akan memperlakukan data pelanggan yang terdaftar sebagai informasi yang rahasia, kecuali diwajibkan oleh peraturan perundang-undangan, pemerintah atau pengadilan, untuk membuka data tersebut.</li>
                <li>Apabila salah satu ketentuan-ketentuan ini dianggap tidak berlaku, ilegal, atau tidak dapat dilaksanakan berdasarkan ketentuan hukum yang berlaku, maka keabsahan dan keberlakuan atas ketentuan lainnya tidak terpengaruh dan ketentuan-ketentuan yang dianggap tidak berlaku, ilegal, atau tidak dapat dilaksanakan tersebut dianggap dihapuskan.</li>
                <li>Syarat dan Ketentuan ini berlaku hanya jika tidak dilarang oleh ketentuan perundang-undangan. Untuk menghindari keraguan, telah disetujui dan dinyatakan secara khusus, namun tanpa pembatasan, bahwa hal-hal di sini tidak dianggap sebagai usaha untuk mengesampingkan ketentuan-ketentuan dalam Undang-undang No. 8 Tahun 1999 tentang Perlindungan Konsumen, jika dan di mana Hukum tersebut berlaku.</li>
                <li>Syarat dan Ketentuan ini akan diatur berdasarkan hukum Indonesia, tidak termasuk ketentuan mengenai konflik hukum. Para Pihak menyetujui untuk menyerahkan yurisdiksi secara eksklusif kepada pengadilan di Indonesia. Para pihak setuju untuk mengesampingkan pasal 1266 Kitab Undang-undang Hukum Perdata sejauh mengenai diperlukannya persetujuan pengadilan terlebih dahulu untuk pembatalan atau pengakhiran perjanjian di antara para pihak.</li>
                <li>Di dalam interpretasi Syarat dan Ketentuan ini, istilah tunggal mencakup jamak dan sebaliknya, kata yang mengacu kepada jenis kelamin tertentu berlaku pula untuk jenis kelamin lainnya dan, apabila ada lebih dari satu orang, kewajiban dan tanggung jawabnya akan mengikat masing-masing orang tersebut secara tanggung renteng.</li>
                <li>Dalam hal terdapat konflik atau inkonsistensi dalam petunjuk kegunaan, syarat dan jaminan pada Paket Perdana dan syarat dan dan ketentuan ini, inkonsistensi tersebut akan diselesaikan dengan memberikan prioritas dengan urutan sebagai berikut ini: syarat dan ketentuan ini, syarat dan ketentuan yang terdapat di dalam Paket Perdana, petunjuk penggunaan.</li>
                <li>Syarat dan Ketentuan merupakan seluruh perjanjian antara para pihak terkait dengan subyek masalah yang diatur di sini dan menggantikan seluruh syarat dan ketentuan, pemahaman, pernyataan dan jaminan sebelumnya terkait dengan subyek masalah tersebut. </li>
              </ol>
        </div><!-- end #contentPromo -->
    </div><!-- end #promoDetail -->
</div><!-- end #container -->